source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/crspybits/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target ‘Tests’ do
	pod 'Google/SignIn'
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'SMSyncServer', :path => '../iOSFramework'
	# pod 'SMSyncServer' # SMSyncServer imports SMCoreLib, which imports AFNetworking
	# pod 'SMCoreLib' # SMCoreLib imports AFNetworking
	
	target ‘XCTests’ do
		inherit! :search_paths
		pod 'Google/SignIn'
	end
end


